[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[sources]
NearestNeighbors = {path = ".."}
