[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"

[sources]
NearestNeighbors = {path = ".."}
